	<!--OYMFOOT.INC START-->
<!--$pageZoomが定義されていればfixedを設定しない。fixed<--画面のフッタ部に自動で移動-->
<!--fixedでviewport、user-scalable=noに固定される。-->
	<div class="footer" data-role="footer" data-theme="a">
	<div class="rhead">仕様名：<?php echo $_SESSION["仕様名"] ?></div>
	<div class="lhead">エンジン品番：<?php echo $_SESSION["エンジン品番"] ?></div>
	<div class="chead">号機：<?php echo $_SESSION["号機"] ?></div>
	</div>
	<!--OYMFOOT.INC END-->
